Anovos config file desc
anovos/anovos-docs pull request #32
Opened 2022-02-01 20:00 UTC by kajanansangar

creating this pull request and assigning it to Nisha for review

2022-02-15 10:59 UTC, ionicsolutions requested changes

2022-02-15 10:59 UTC, ionicsolutions commented on docs/anovos-config-file-desc/index.md
> +
Not sure whether this is the best place to keep and update this information?

2022-02-15 10:59 UTC, ionicsolutions commented on docs/anovos-config-file-desc/index.md
> +            can be passed through this key e.g., delimiter, inferSchema, header.
How do I know what a "valid configuration" is?

2022-02-16 12:53 UTC, sumitgaurav19 commented on docs/anovos-config-file-desc/index.md
> +            running with AWS cloud services)
okay got it @ionicsolutions , I will add azure and colab part too

2022-02-17 10:48 UTC, sumitgaurav19 commented on docs/anovos-config-file-desc/index.md
> +
@ionicsolutions we may need to read the datasets twice or thrice when we are doing joining or concatenating operations in data ingest modules that's why I describe the same again in this section.

2022-02-17 13:54 UTC, sumitgaurav19 commented on docs/anovos-config-file-desc/index.md
> +modules. Let's see each of the keys and its values in detail:
@ionicsolutions I have added a short note on the need to using configuration file

2022-02-17 13:55 UTC, sumitgaurav19 commented on docs/anovos-config-file-desc/index.md
> +            can be passed through this key e.g., delimiter, inferSchema, header.
Got it @ionicsolutions, for that I have attached a link which help the users to understand while file configurations they need to use while reading the dataset.

2022-02-17 13:57 UTC, sumitgaurav19 commented on docs/anovos-config-file-desc/index.md
> +        input dataframe.
For that I have attached the documentation link of data ingest module which will help the users to understand these operations(delete, select, rename, recast, etc). and based on that they decide which options to use.

2022-02-20 12:55 UTC, ionicsolutions requested changes
@sumitgaurav19 Thanks for the answers to my questions!

I have revised the introduction and the first section. Do you have the time to adapt the subsequent sections to this style and structure in time for the release?

@kajanansangar

2022-02-20 12:55 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +Each _Anovos_ configuration file must contain exactly one `input_dataset` block.
@sumitgaurav19 Is this correct?

2022-02-20 12:55 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +First, columns are deleted, then selected, then renamed, and then recast.
@sumitgaurav19 Is this correct?

2022-02-20 13:14 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +
@sumitgaurav19 Can you please add a brief description how to run a Spark job with the configuration file?

Ideally, it would be a trimmed-down, minimal version of https://github.com/anovos/anovos/blob/main/bin/spark-submit.sh#L22

2022-02-22 10:34 UTC, sumitgaurav19 commented on docs/using-anovos/config_file.md
> +Each _Anovos_ configuration file must contain exactly one `input_dataset` block.
Yes @ionicsolutions I think it is correct

2022-02-22 10:37 UTC, sumitgaurav19 commented on docs/using-anovos/config_file.md
> +First, columns are deleted, then selected, then renamed, and then recast.
yes @ionicsolutions it is also correct

2022-02-24 11:08 UTC, sumitgaurav19 commented
> @sumitgaurav19 Thanks for the answers to my questions!
> 
> I have revised the introduction and the first section. Do you have the time to adapt the subsequent sections to this style and structure in time for the release?
> 
> @kajanansangar



> @sumitgaurav19 Thanks for the answers to my questions!
> 
> I have revised the introduction and the first section. Do you have the time to adapt the subsequent sections to this style and structure in time for the release?
> 
> @kajanansangar

Hi @ionicsolutions I have changed the subsequent sections in the same style and structure u mentioned.

2022-02-24 11:14 UTC, sumitgaurav19 commented
@ionicsolutions For this release config file has also updated as transformers and TS modules are added, so I need to add description of those also.

2022-02-24 11:30 UTC, ionicsolutions commented
Hi @sumitgaurav19, thanks for the revision!

If you have time, could you please add some more examples for the different sections? I know that it seems self-evident how to write the configuration but I believe new users will be very happy to have something they can copy and adapt to their needs.

Looking forward to the transformer and time series sections!

I've scheduled my revision of this page for later today, so don't be surprised to see some commits from my side as well.

2022-02-24 11:34 UTC, sumitgaurav19 commented
Okay @ionicsolutions , I will some examples as well as transformers and ts modules in the next commit

2022-02-24 20:20 UTC, ionicsolutions requested changes

2022-02-24 20:20 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +
Here, we need to answer the question: What exactly does that do? Concatenate `dataset1` and `dataset2`?

2022-02-24 20:20 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +
Questions a new user might have at this point:
- Can there be a `dataset3`?
- Do I have to specify a `dataset2`? (Or can I just use e.g. the recast functionality?

2022-02-24 20:20 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +
We need an introduction to this section:
- What is a report?
- Why would I want to specify it?
- Do I need to add this section to every config file?

2022-02-24 20:20 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +*Attaching the documentation link of modules to get better idea what these modules actually do and thier output: [Data Analyzer](https://github.com/anovos/anovos-docs/blob/main/docs/anovos-modules-ov
Can we be more specific? What is a user going to learn there?

2022-03-01 10:04 UTC, ionicsolutions requested changes
The section on the timeseries analysis still lacks information.

2022-03-01 10:04 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `id_col`: 'id_column'
This is not helpful ;-)

2022-03-01 10:04 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `auto_detection`: This takes Boolean type input -- `True` or `False`. If True, it will help produce the output containing a transformation through auto timestamp / date detection by reading the ing
What exactly is auto-detected? The format of the timestamps?

2022-03-01 10:04 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `tz_offset`: Timezone offset (Option to chose between options like Local, GMT, UTC, etc.). Default option is set as "Local".
Where can I find a list of all possible options?

2022-03-01 10:04 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `inspection`: This takes Boolean type input -- `True` or `False`.
What does this flag do?

2022-03-01 10:04 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `analysis_level`: Option to choose between "Daily" or "Weekly" or "Hourly". Daily is chosen as default. If "Daily" is selected as the output type, the daily view is populated ; If it's "Hourly", th
Which part of the API doc describes this in more detail? We should add a link.

2022-03-01 10:04 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `max_days`: Max days upto which the data will be aggregated. If we've a dataset containing a timestamp / date field with very high number of unique dates (Let's say beyond 20 years worth of daily d
Is this counted from today? If so, is "today" in the same timezone as specified above? Can I set a fixed timeframe with `start_date` and `end_date`?

2022-03-07 13:46 UTC, ionicsolutions requested changes

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +   If set to `weekly`, the display it per individual weekdays (1-7) as captured.
I believe that this is very difficult to understand without knowing a lot about the time series analyzer already. Is there a specific section or examples we can point the reader to?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +list of different metrics used to generate descriptive statistics [global_summary, measures_of_count, measures_of_centralTendency, measures_of_cardinality, measures_of_dispersion, measures_of_percent
Is this list complete?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `drop_cols`: (list format or string of col names separated by `|`). It is used to specify the columns that need to be dropped from list_of_cols before duplicate detection
Are they dropped from the dataset entirely or just while duplicates are detected?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `treatment`: It takes Boolean type input -- `True` or `False`. If true, duplicate rows are removed from the input dataset.
A user might wonder: Why would I even add this block without setting `treatment: True`?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `treatment_threshold`: It takes a value between `0` to `1` with default 0.8, which means 80% of columns are allowed to be Null per row. If it is more than the threshold, then it is flagged and if t
Where can I find these flags? Will a column be added to the dataframe?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `treatment`: This takes Boolean type input -- `True` or `False`. If true, rows with high null columns (defined by treatment_threshold argument) are removed from the input dataset.
A user might wonder: Why would I even add this block without setting `treatment: True`?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `treatment`: This takes Boolean type input -- `True` or `False`. If true, invalid values are replaced as null and treated as missing.
A user might wonder: Why would I even add this block without setting `treatment: True`?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `Treatment`: This takes Boolean type input -- `True` or `False`. If true, columns above IDness threshold are removed.
A user might wonder: Why would I even add this block without setting `treatment: True`?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `Treatment`: This takes Boolean type input -- `True` or `False`. If true, columns above biasedness threshold are removed.
A user might wonder: Why would I even add this block without setting `treatment: True`?

2022-03-07 13:46 UTC, ionicsolutions commented on docs/using-anovos/config_file.md
> +- `treatment`: takes Boolean type input -- `True` or `False`. If true, missing values are treated as per treatment_method argument
A user might wonder: Why would I even add this block without setting `treatment: True`?

2022-03-07 14:01 UTC, sumitgaurav19 commented on docs/using-anovos/config_file.md
> +list of different metrics used to generate descriptive statistics [global_summary, measures_of_count, measures_of_centralTendency, measures_of_cardinality, measures_of_dispersion, measures_of_percent
yes

2022-03-07 14:01 UTC, sumitgaurav19 commented on docs/using-anovos/config_file.md
> +- `drop_cols`: (list format or string of col names separated by `|`). It is used to specify the columns that need to be dropped from list_of_cols before duplicate detection
just while duplicate detection.

2022-03-07 14:10 UTC, sumitgaurav19 commented on docs/using-anovos/config_file.md
> +- `treatment_threshold`: It takes a value between `0` to `1` with default 0.8, which means 80% of columns are allowed to be Null per row. If it is more than the threshold, then it is flagged and if t
@ionicsolutions, not any column gonna be added to the dataframe. Here if treatment is True, Then some rows will be removed if and only if the Total null present in that particular row is greater than a treatment threshold value.

2022-03-08 05:55 UTC, sumitgaurav19 commented on docs/using-anovos/config_file.md
> +- `treatment`: It takes Boolean type input -- `True` or `False`. If true, duplicate rows are removed from the input dataset.
@ionicsolutions, if **treatment: True** then it will generate the stats like a number of duplicate rows as well as removed duplicate rows from the input dataset. 
If **treatment: False**, then it will generate only the stats (number of duplicate rows).

So even if user use this block **without setting treatment: True**, they will atleast able to see the stats.

same answer for other comments as well

2022-03-23 11:37 UTC, ionicsolutions commented
@sumitgaurav19 @kajanansangar I have added numerous TODOs in the page where you or a member of your team needs to clarify descriptions, add links, or provide examples.

2022-03-28 07:39 UTC, sumitgaurav19 commented
@ionicsolutions I have seen the TODOS that you have added, I will work on it.

2022-03-30 10:39 UTC, sinuochen commented
I have addressed the TODOs in config_file.md.

Some comments are wrt the module itself, I removed them for now and will discuss with Nisha for possible improvements:
* outlier_categories
    * Can I change the name of the new category to something else? What happens if there already is a category others?
* cat_to_num_unsupervised
    * method_type: shouldn't this be label_encoding and onehot_encoding to be consistent with the other methods?

A few comments were removed because:
* Users can use multiple functions in one section as well but ideally list_of_cols should be mutually exclusive if used functions are making similar effect (like PCA_latentFeatures and autoencoder_latentFeatures)
* stats_missing argument needs to be removed because it is handled by main.py

2022-03-30 12:18 UTC, sourjyasen07 commented
changes are good to be merged for now. further updates on the documents to be taken up eventually

2022-03-30 12:22 UTC, merged