Azure databricks docs
anovos/anovos-docs pull request #33
Opened 2022-02-01 21:01 UTC by kajanansangar

Creating PR here and assigning it to @sourjyas for review

2022-02-15 10:45 UTC, ionicsolutions requested changes

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +Clone the Anovos Repository on local environment using command:
A new user will wonder: Is "local environment" my own computer or is this something on Azure?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**Step1: Installing/Downloading Anovos**
I believe we need to set up a user account etc. first?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +in azure databricks.
Why do I need to create my own wheel? Why can't I just install from PyPI?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +Clone the Anovos Repository on local environment using command:
Also, please explain _why_ I need to do this. What is the goal of this step?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**Step3: Copy necessary files to Databricks File System (DBFS) in Azure
This is very confusing for a new user.

_Why_ do I need to do this? Which of these things to I need to do if I want to process my own data?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +    necessary functions.
How? (E.g., add an example or link to a different doc page)

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +Copy the following files to DBFS directly from UI or from CLI commands:
How do I do this? Can you show the commands?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +    changes depend upon the dataset being used.
How do I do this? I don't think that's something a new user will know how to do from this very brief description.

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**Steps to copy files to DBFS using UI**
Is this the description that I asked for above? If so, it should be mentioned above that the detailed instructions follow down here.

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +    clicking ‘drop files to upload, or click to browse’, users will be
In addition, you could link to the relevant parts of the Azure docs.

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**Step3: Creating jobs for running anovos by initiating cluster**
My main question as a new user would be: How much does this cost? Do I need specific credentials?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +> For running in python 3.8 – scala 2.12, spark 3.x.x
As a new user I wonder: How do I choose?

Do we even need to present two different options here?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +iii.  **Autopilot Options –** Enable autoscaling should be on
"should" or "has to be"?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +> configurations according to jobs complexity
How do I know what I need? Can we point the users somewhere? Are there metrics I should watch and base my decision on?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +> Note: we can also give location of DBFS path directly by clicking on
Why would I want to use one of the options above the other?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +will be created successfully.
That's quite a bold statement ;-) I don't think we can say that they "_will_ be created _successfully_", there are many reasons the creation might fail.

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +available.
Where? How do I configure this? Where can I learn more? (e.g., link to Azure docs)

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +Once the job finishes successfully, users will be able to see their logs
Where do I have to look?

2022-02-15 10:45 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +The reports and all the intermediate outputs are saved at the required
This is very confusing to new users because you're using Anovos-specific terms that only your team knows so far.

Tell the users exactly where they configured the path and where they need to go to find the files. Take them along :-)

2022-02-24 20:03 UTC, ionicsolutions commented
@sourjyasen07 Just so that I can plan accordingly: Will you address the open remarks in time for the release?

2022-03-26 18:00 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +in azure databricks.
Why do I need to do this? These are essentially the instructions for creating a wheel for Anovos.

Why can't users just download the wheel from PyPI (at https://pypi.org/project/anovos/#files) instead of going through the hassle of building it themselves? It doesn't look like any special options are included here.

2022-03-26 18:01 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +3.  Copy the URL of databricks host and the personal access tokens
Where do I find this information?

2022-03-26 18:01 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +2.  Make sure the personal access tokens have already generated
How do I make sure?

2022-03-26 18:02 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +4.  Configure the CLI using command – databricks configure --token
Please link to the relevant documentation in case this doesn't work for the user.

2022-03-26 18:02 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**DBFS CLI Command for copy in Azure Databricks:**
Why do I need this command?

2022-03-26 18:02 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +
Please explain what we're going to do in this section

2022-03-26 18:03 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**Note**Attaching link that describes all the information related to cluster configurations.
When should a user follow that link? What information would they need from there?

2022-03-26 18:03 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +iii.  **Autopilot Options –** Enable autoscaling has to be on
Why does it need to be on? Is this true in general for Anovos? Or just for this demo?

2022-03-26 18:04 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +> configurations according to jobs complexity.
How do I know which option to choose? How do I know if my job is too complex for the currently chosen machines?

2022-03-26 18:05 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +
I doubt that users will be able to follow this instruction. This might work well as a memory aid if you've done this step/configuration before but not for someone encountering it the first time.

2022-03-26 18:05 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +in azure databricks.
See above. I don't think this is necessary.

2022-05-16 18:53 UTC, ionicsolutions commented on docs/using-anovos/setting-up/on_azure_databricks.md
> +**TODO: Why is main.py not shipped within the wheel? How do we ensure that the versions match?**
@ranjanravish Can we include the main.py within the wheel? Users should not have to go to the GitHub repository to get it and the `main.py` on GitHub might not match the version of Anovos they're running.

2022-05-18 11:06 UTC, ionicsolutions commented
@ranjanravish Can you please have a look at the shortened and revised DBFS tutorial? I've added a number of questions/todo comments directly in the Markdown. I believe there is no need to manually create or upload wheels, we can just tell the user to fetch it directly from PyPI through the Databricks interface.

2022-05-22 22:07 UTC, maustin10 commented
I was confused with the link above with Todo's 
https://github.com/anovos/anovos-docs/pull/33/commits/1b8f673205d9492773e27fe8b2c9b4e9947ccffe

there is a Step 4, then Step 3... I assume the Step 4 heading at this point is in error? 


<img width="468" alt="image" src="https://user-images.githubusercontent.com/5631981/169716252-4c5eae7c-bc3b-49e5-b662-a4c47e57f347.png">

Then, assuming this is Step 3, it says to create a main.py 

<img width="468" alt="image" src="https://user-images.githubusercontent.com/5631981/169716309-5695e412-ee04-4942-ac82-e0bc4437afa3.png">

but in Step 2, we uploaded the other main.py, is this different? 

I assumed there were essentially two main.py's , so tried the first one as follows: 

import sys
from anovos import workflow

workflow.run(config_path=sys.argv[1], run_type="databricks")

however, get this error: 

<img width="993" alt="image" src="https://user-images.githubusercontent.com/5631981/169717963-12375ed2-2c94-433d-9294-5b70fcf66fd9.png">

checked this as well in a notebook (to verify that import anovos itself was there) and got same error 

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/5631981/169717984-77202abc-ad72-4192-83ad-b3638effc71f.png">

2022-05-23 20:50 UTC, ionicsolutions commented
Hi @maustin10, thanks for trying this guide and the feedback!

As you have probably already guessed from looking at the history of this PR, I'm currently working with @ranjanravish on getting this guide into shape. So please consider it a work in progress.

We have used this guide as an opportunity to simplify a lot of things around using _Anovos_ on third-party services. One of these concerns the role of the `main.py` file. Currently, users need to fetch the `main.py` that matches the wheel file's version from GitHub in order to run _Anovos_ workflows. This is not only inconvenient but is a source of errors if there is a mismatch between the wheel file's version and the `main.py`'s version.

We've addressed this problem in [PR 186](https://github.com/anovos/anovos/pull/186), which has not yet been merged. The guide that's taking shape here already reflects this change.

CC @kajanansangar

2022-05-27 12:16 UTC, ionicsolutions commented
@ranjanravish Do we need to repeat the entire guide in the second part or is there a way to just describe how to mount the container and which paths to change? You're the expert here, obviously, but to me it seems that at the end of the day there's not a lot of differences between the two variants.

2022-05-27 13:12 UTC, merged