Feature Explorer and Recommender Docs
anovos/anovos-docs pull request #38
Opened 2022-02-22 19:28 UTC by dattranm

Add Feature Explorer and Recommender Docs:
- Create new folder, feature_recommender, inside anovos-modules-overview and push docs in index.md
- Add Feature Explorer and Recommender to Overview section (overview/index.md)
- Add Feature Explorer and Recommender to mkdocs.yml to serve the following section.

2022-02-23 00:03 UTC, kajanansangar requested changes
Changes  are proposed

2022-02-23 00:03 UTC, kajanansangar commented on docs/anovos-modules-overview/overview/index.md
> +6. **Feature Explorer and Recommender**:
this should be moved up to number 4

2022-02-23 00:03 UTC, kajanansangar commented on docs/anovos-modules-overview/overview/index.md
>  Note: Upcoming Modules - Feature Wiki, Feature store, Auto ML, ML Flow Integration
This should be changed to Feature Store Integration, Auto ML, & ML Flow Integration

2022-02-24 20:01 UTC, ionicsolutions commented
@dattranm For the most part, we will integrate this text into the API docs, i.e., we will store it in the main repository right with the source code.

Let me know when you're done here and I'll revise and move the text so that it's included in the documentation :-)

2022-02-28 21:27 UTC, kajanansangar commented
@ionicsolutions respective changes here should be copied over to anovos/anovos since the anovos/anovos-doc is no more available

2022-03-01 09:41 UTC, ionicsolutions commented
@kajanansangar Should I take care of that or will @dattranm add his work in the main repo?

2022-03-01 23:58 UTC, merged